---
title: "Takım: What R We Doing?"
sidebar: false 
---

MUY665-İş Analitiği dersi takım sayfamıza hoş geldiniz.

Burada iş analitiği çalışmalarımızı paylaşıyoruz.

Lütfen faaliyetlerimizi görmek için için bizi takipte kalın.

## Takım Üyeleri

1.  [Osman Erel](/takim/osmanerel.qmd)

2.  H[atice Deniz Akben](/takim/hdenizakbel.qmd)

3.  [Muhammed Taha Günday](/takim/mtgunday.qmd)

4.  [Beril Aksoy](/takim/berilaksoy.qmd)

5.  [Selin Öksüz](/takim/selinoksuz.qmd)

6.  [Selin Kaya](/takim/selinkaya.qmd)

## Proje Adı

MUY665 Projesi

## Proje Konusu

Örnek: Bu projede MUY660-İş Analitiği ders içeriğinin analitik yaklaşımlarla iyileştirilmesini hedefledik. Bu doğrultuda tüm üniversitelerdeki benzer derslerin verisini toplayarak bir veri seti oluşturduk Analiz için …….. yöntemleri kullanarak, ……. çalışmaları yaptık Sonuç olarak, MUY660-İş Analitiği dersinin dünyadaki tüm derslerden daha iyi olduğunu ve bu dersi aldığımız için çok mutlu olduğumuzu tespit ettik.

## Veri Seti Hakkında Özet Bilgi

## Sonuçlar

Burada key takeways verilmelidir. En az 3 en fazla 5 madde ile çarpıcı sonuçlar sunulmalıdır.
